import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-gray-50 text-gray-900 font-sans h-screen flex overflow-hidden">
        <TRPCReactProvider>
          {/* Sidebar */}
          <aside className="w-64 bg-white border-r border-gray-200 flex flex-col h-full">
            <div className="p-6">
              <h1 className="text-2xl font-bold text-indigo-600">AccApp</h1>
              <p className="text-sm text-gray-500 mt-1">Smart Accounting</p>
            </div>
            <nav className="flex-1 px-4 space-y-2">
              <Link
                href="/"
                className="block px-4 py-2 rounded-md hover:bg-indigo-50 hover:text-indigo-600 font-medium transition-colors"
              >
                Dashboard
              </Link>
              <Link
                href="/accounts"
                className="block px-4 py-2 rounded-md hover:bg-indigo-50 hover:text-indigo-600 font-medium transition-colors"
              >
                Chart of Accounts
              </Link>
              <Link
                href="/journal"
                className="block px-4 py-2 rounded-md hover:bg-indigo-50 hover:text-indigo-600 font-medium transition-colors"
              >
                Journal Entries
              </Link>
            </nav>
            <div className="p-4 border-t border-gray-200">
              <p className="text-xs text-gray-400 text-center">
                Built with T3 Stack
              </p>
            </div>
          </aside>

          {/* Main Content */}
          <main className="flex-1 overflow-y-auto p-8 bg-gray-50">
            {children}
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
